title: POPDG
description: >-
  A brief description of the POPDG project. Welcome.
baseurl: ""
url: "https://luke-luo1.github.io/POPDG"

# theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Other configurations
markdown: kramdown
highlighter: rouge
